---
:api_key: 3c81365f3b2e0c18ec5837831ff7b65f
:password: 91fc8dabc4aec46b36fc1717e624dd9f
:theme_id: '5'
:preview_url: https://fabricaesportes.commercesuite.com.br/loja/loja.php?loja=1016705&opencode_theme=60a6a3f05daea
